services:
  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    ports:
      - "3000:80"
    restart: always

  mysql:
    image: mysql:8.0
    environment:
      MYSQL_ROOT_PASSWORD: root123teste
      MYSQL_DATABASE: testedb
      MYSQL_USER: server
      MYSQL_PASSWORD: 123teste
    ports:
      - "3306:3306"
    volumes:
      - mysql_data:/var/lib/mysql
      - ./init-db.sql:/docker-entrypoint-initdb.d/init-db.sql

  backend:
    build: ./backend
    environment:
      MYSQL_HOST: mysql
      MYSQL_USER: server
      MYSQL_PASSWORD: 123teste
      MYSQL_DATABASE: testedb
      PORT: 5000
    ports:
      - "5000:5000"
    depends_on:
      - mysql

volumes:
  mysql_data: